name: Release Logica Sandbox API Docker Image

on:
  push:
    branches: ['main']

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rise8-us/logica-sandbox-infra/api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/build-push-action@v5.1.0
        with:
          images: ghcr.io/rise8-us/logica-sandbox-infra/api
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
